"""Initial migration

Revision ID: 68c7dc142aba
Revises:
Create Date: 2026-01-11 13:42:30.302339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import database_models


# revision identifiers, used by Alembic.
revision: str = '68c7dc142aba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_name')
    )
    op.create_table('prices',
    sa.Column('price_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('price_id'),
    sa.UniqueConstraint('symbol', 'timestamp', name='_symbol_timestamp_uc')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_order_id', database_models.UUID(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.CheckConstraint("order_type IN ('BUY', 'SELL')", name='order_type_check'),
    sa.CheckConstraint("status IN ('pending', 'executed', 'cancelled', 'failed')", name='status_check'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_table('positions',
    sa.Column('position_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('position_id'),
    sa.UniqueConstraint('account_id', 'symbol', name='_account_symbol_uc')
    )
    op.create_table('ledger',
    sa.Column('entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('change', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('new_balance', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger')
    op.drop_table('positions')
    op.drop_table('orders')
    op.drop_table('prices')
    op.drop_table('accounts')
    # ### end Alembic commands ###
